---
- name: Configure Nginx on EC2 instance
  hosts: nginx_servers
  become: yes
  gather_facts: yes

  tasks:
  - name: Update package cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
    when: ansible_os_family == "Debian"

  - name: Install Nginx
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"

  - name: Start and enable Nginx service
    systemd:
      name: nginx
      state: started
      enabled: yes

  - name: Create custom Nginx configuration
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/sites-available/default
      backup: yes
    notify: restart nginx

  - name: Create a simple index.html
    template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: www-data
      group: www-data
      mode: '0644'

  - name: Check if Nginx is running
    service:
      name: nginx
      state: started

  - name: Wait for Nginx to be fully ready
    wait_for:
      port: 80
      host: "{{ ansible_default_ipv4.address }}"
      delay: 5
      timeout: 30

  - name: Verify Nginx is accessible
    uri:
      url: "http://localhost"
      method: GET
      status_code: 200
      timeout: 20
    retries: 3
    delay: 5
    ignore_errors: yes
    register: nginx_local_check

  - name: Display local check result
    debug:
      msg: "Local Nginx check: {{ 'SUCCESS' if nginx_local_check.status == 200 else 'FAILED' }}"

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
